    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            
            // HAPUS BARIS INI: optimizationPasses 0 
            
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),
                          'proguard-rules.pro'

            if (android.hasProperty("signingConfigs")) {
                if (signingConfigs.hasProperty("release")) {
                    signingConfig = signingConfigs.release
                }
                if (signingConfigs.hasProperty("beta")) {
                    signingConfig = signingConfigs.beta
                }
            }
        }
        // ... debug block tetap sama ...
    }
