name: Bangun OFA-PTT
run-name: Bangun OFA-PTT

on:
  push:
    branches:
      - ptt-new
  pull_request:
    branches:
      - ptt-new
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Ambil kode
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      # ✅ PERSIS SARAN GITHUB — TANPA api-level, TANPA build-tools lama
      - name: Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0
          accept-android-sdk-licenses: true

      - name: Lokasi SDK
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Beri izin
        run: chmod +x gradlew libraries/humla/gradlew

      - name: Bangun SpongyCastle
        run: |
          cd libraries/humla/libs/humla-spongycastle
          ../../../../gradlew jar
          cd ../../../../

      - name: Bangun APK Debug
        run: ./gradlew assembleDebug --no-daemon

      - name: Simpan APK
        uses: actions/upload-artifact@v4
        with:
          name: OFA-PTT-DEBUG
          path: "app/build/outputs/apk/debug/*.apk"
